// Find the difference

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/

let s = "";
let t = "y";

const findDiff = (s, t) => {
  let sMap = new Map();
  let tMap = new Map();
  for (let i = 0; i < s.length; i++) {
    if (sMap.has(s.charAt(i))) {
      sMap.set(s.charAt(i), sMap.get(s.charAt(i)) + 1);
    } else {
      sMap.set(s.charAt(i), 1);
    }
  }

  for (let j = 0; j < t.length; j++) {
    if (tMap.has(t.charAt(j))) {
      tMap.set(t.charAt(j), tMap.get(t.charAt(j)) + 1);
    } else {
      tMap.set(t.charAt(j), 1);
    }
  }

  for (const [key, val] of tMap) {
    if (!sMap.has(key)) return key;
    else if (sMap.has(key) && sMap.get(key) !== tMap.get(key)) {
      return key;
    } else continue;
  }
};
console.log(findDiff(s, t));
